# Generated by Django 5.0 on 2023-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
